pg12:
  image:
    tag: 12.9.0-debian-10-r62
    # debug: true

  existingSecret: pg12-creds

  replication:
    enabled: false

  persistence:
    existingClaim: "pg12-data-claim"

  primary:
    nodeSelector:
      db: "true"

  tls:
    enabled: true
    certificatesSecret: pg12-certs
    certCAFilename: "ca.crt"
    certFilename: "pg12.crt"
    certKeyFilename: "pg12.key"

  volumePermissions:
    enabled: true  # needed to ensure correct permission for certificate files in `tls` section above

  service:
    type: LoadBalancer
    loadBalancerIP: 172.22.18.33  # part of MetalLB private pool
    port: 6432
    externalTrafficPolicy: Local  # preserve client source IP to target pod
