pg12:
  image:
    tag: 12.9.0-debian-10-r62
    # debug: true

  existingSecret: pg12-creds

  replication:
    enabled: false

  persistence:
    existingClaim: "pg12-data-claim"

  primary:
    nodeSelector:
      db: "true"
