apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager

resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
  - ./issuer-self-signed.yaml
  - ./issuer-cluster-ca.yaml
  - ./issuer-cluster-ca-signing-secret.yaml
