apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml
  - ./issuer-self-signed.yaml
