apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: probe-prometheus-rules
  namespace: monitoring
spec:
  groups:
  - name: probe.rules
    rules:
    - alert: EndpointDown
      annotations:
        summary: "Endpoint {{ $labels.instance }} down"
      expr: probe_success == 0
      for: 2m
      labels:
        severity: critical
