# likely unused after upgrade to Grafana 8.2.x and turning of legacy alerts
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notifiers-brad
  namespace: monitoring
data:
  brad.yaml: |
    apiVersion: 1
    notifiers:
    - name: "Brad - Email"
      type: email
      org_id: 1
      uid: brad-email
      is_default: true
      send_reminder: true
      frequency: 30m
      settings:
        addresses: brad-k8s-alerts-rqH3@fewerhassles.com
        uploadImage: true
