apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-monitoring-dashboard-view
  namespace: monitoring-dashboards
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: monitoring
roleRef:
  kind: Role
  name: monitoring-dashboard-view
  apiGroup: rbac.authorization.k8s.io
