# for Grafana datasource associated with the `pg12` database instance
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-pg12-client-certificate
  namespace: monitoring
spec:
  secretName: grafana-pg12-client-cert
  commonName: grafana
  dnsNames:
    - grafana
  privateKey:
    algorithm: ECDSA
  usages:
    - client auth

  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
