apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: monitoring
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        isDefault: true
        access: proxy
        url: http://prometheus-k8s.monitoring.svc:9090
        editable: "false"
        version: 1
