apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
  - github.com/bfritz/homelab-apps/vendor/kube-prometheus
  - ./prometheus_extra/additional-scrape-configs.yaml

patches:
  - patch: |-
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: k8s
        namespace: monitoring
      spec:
        additionalScrapeConfigs:
          name: additional-scrape-configs
          key: prometheus-additional.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
            - name: grafana
              env:
              - name: GF_SMTP_ENABLED
                value: "true"
              - name: GF_SMTP_HOST
                value: mail.fewerhassles.com:587
