apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
  - github.com/bfritz/homelab-apps/vendor/kube-prometheus
  - ./prometheus_extra/additional-scrape-configs.yaml
  - ./grafana-notifiers-brad.yaml

images:
  - name: grafana/grafana
    newTag:
    digest: sha256:d6325d20f78cd306b4f8a9d0057ea7022a34d273553034d3d871040c3db37fc3 # 8.2.3 for linux/amd64

patches:
  - patch: |-
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: k8s
        namespace: monitoring
      spec:
        additionalScrapeConfigs:
          name: additional-scrape-configs
          key: prometheus-additional.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
            - name: grafana
              env:
              - name: GF_ANALYTICS_REPORTING_ENABLED
                value: "false"
              - name: GF_CHECK_FOR_UPDATES
                value: "false"
              - name: GF_UNIFIED_ALERTING_ENABLED
                value: "true"
              - name: GF_PLUGINS_ENABLE_ALPHA
                value: "true" # for AlertManager data source https://grafana.com/docs/grafana/latest/datasources/alertmanager/ @ v8.2
              - name: GF_ALERTING_ENABLED # legacy alerts
                value: "false"
              - name: GF_SMTP_ENABLED
                value: "true"
              - name: GF_SMTP_HOST
                value: mail.fewerhassles.com:587
              volumeMounts:
              - mountPath: /etc/grafana/provisioning/notifiers
                name: grafana-notifiers
                readOnly: false
            volumes:
            - name: grafana-notifiers
              configMap:
                name: grafana-notifiers-brad
