apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
  - github.com/bfritz/homelab-apps/vendor/kube-prometheus
  - ./alertmanager-email-brad.yaml
  - ./alertmanager-ingress.yaml
  - ./grafana-dashboards-app.yaml
  - ./grafana-ingress.yaml
  - ./grafana-monitoring-dashboards-view-role.yaml
  - ./grafana-notifiers-brad.yaml
  - ./grafana-rolebinding.yaml
  - ./probes-key-public-ips.yaml
  - ./prometheus-ingress.yaml
  - ./prometheus_extra/additional-scrape-configs.yaml

images:
  - name: kiwigrid/k8s-sidecar
    digest: sha256:35654389f8a9b7816193a4811cf3ceb6cf309ece8874e84b3d2d8399e618059b # 1.14.2

patches:
  - patch: |-
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: k8s
        namespace: monitoring
      spec:
        additionalScrapeConfigs:
          name: additional-scrape-configs
          key: prometheus-additional.yaml

  - patch: |-
      apiVersion: monitoring.coreos.com/v1
      kind: Alertmanager
      metadata:
        name: main
        namespace: monitoring
      spec:
        alertmanagerConfigSelector:
          matchLabels:
            alertmanagerConfig: active

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
            - name: grafana
              env:
              - name: GF_ANALYTICS_REPORTING_ENABLED
                value: "false"
              - name: GF_CHECK_FOR_UPDATES
                value: "false"
              - name: GF_UNIFIED_ALERTING_ENABLED
                value: "true"
              - name: GF_PLUGINS_ENABLE_ALPHA
                value: "true" # for AlertManager data source https://grafana.com/docs/grafana/latest/datasources/alertmanager/ @ v8.2
              - name: GF_ALERTING_ENABLED # legacy alerts
                value: "false"
              - name: GF_SMTP_ENABLED
                value: "true"
              - name: GF_SMTP_HOST
                value: mail.fewerhassles.com:587
              volumeMounts:
              - name: grafana-notifiers
                mountPath: /etc/grafana/provisioning/notifiers
                readOnly: false
              - name: sc-dashboard-volume
                mountPath: "/grafana-dashboard-definitions/cm"
            - name: grafana-sc-dashboard
              image: "kiwigrid/k8s-sidecar"
              imagePullPolicy: IfNotPresent
              env:
                - name: METHOD
                  value: "WATCH"
                - name: LABEL
                  value: "grafana_dashboard"
                - name: FOLDER
                  value: "/tmp/dashboards"
                - name: RESOURCE
                  value: "configmap"
                - name: NAMESPACE
                  value: "monitoring-dashboards"
                - name: UNIQUE_FILENAMES
                  value: "true"
              volumeMounts:
              - name: sc-dashboard-volume
                mountPath: "/tmp/dashboards"
            volumes:
            - name: grafana-notifiers
              configMap:
                name: grafana-notifiers-brad
            - name: sc-dashboard-volume
              emptyDir: {}

  # enable ICMP for blackbox-exporter
  - path: blackbox-exporter-configuration.yaml
    target:
      name: blackbox-exporter-configuration
      kind: ConfigMap

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: blackbox-exporter
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
            - name: blackbox-exporter
              securityContext:
                runAsUser: 0 # to override the default of 65534 (nobody)
                runAsNonRoot: false
                capabilities:
                  drop: ["ALL"]
                  add: ["NET_RAW"]

  # add supplemental grafana dashboard provider for ConfigMap backed dashboards
  - path: grafana-dashboards-configuration.yaml
    target:
      name: grafana-dashboards
      kind: ConfigMap
