apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
  - github.com/bfritz/homelab-apps/vendor/kube-prometheus
  - ./prometheus_extra/additional-scrape-configs.yaml
  - ./grafana-notifiers-brad.yaml

images:
  - name: grafana/grafana
    newTag:
    digest: sha256:f9139cfb93732c7b2e65c2c3d7fa240139501551d83bd5b94e5d6f2ccfa9cd7c # 8.1.7 for linux/amd64

patches:
  - patch: |-
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: k8s
        namespace: monitoring
      spec:
        additionalScrapeConfigs:
          name: additional-scrape-configs
          key: prometheus-additional.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
            - name: grafana
              env:
              - name: GF_SMTP_ENABLED
                value: "true"
              - name: GF_SMTP_HOST
                value: mail.fewerhassles.com:587
              volumeMounts:
              - mountPath: /etc/grafana/provisioning/notifiers
                name: grafana-notifiers
                readOnly: false
            volumes:
            - name: grafana-notifiers
              configMap:
                name: grafana-notifiers-brad
