kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: public-https-endpoints
  namespace: monitoring
spec:
  interval: 120s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - https://indyscala.org
      - https://www.indyscala.org
