kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: internal-ips
  namespace: monitoring
spec:
  interval: 5s
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - isp-gw
      - nas
      - smtp
      - vpn-gw
