apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-a
  labels:
    app: prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nas
    path: "/storage/k8s/nfs/prometheus/a"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-b
  labels:
    app: prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nas
    path: "/storage/k8s/nfs/prometheus/b"
  mountOptions:
    - nfsvers=4.2
