apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-backup
  labels:
    name: pg-backup
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas
    path: "/storage/k8s/nfs/pg/backup"
  mountOptions:
    - nfsvers=4.2
