apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg12-server-certificate
  namespace: database
spec:
  secretName: pg12-server-cert
  commonName: pg12
  dnsNames:
    - pg12
    - app-database-pg12.database.svc
  privateKey:
    algorithm: ECDSA
  usages:
    - server auth

  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
