haproxy-ingress-private:
  controller:
    ingressClass: haproxy-private
    service:
      annotations:
        metallb.universe.tf/address-pool: private-pool
        metallb.universe.tf/allow-shared-ip: private-main
      loadBalancerIP: 172.22.18.32
      externalTrafficPolicy: Cluster
    stats:
      enabled: true
      port: 1936
    metrics:
      enabled: true
      embedded: true
    serviceMonitor:
      enabled: true
    logs: # access logs
      enabled: true
    config:
      config-frontend: |
        capture request header User-Agent len 100

haproxy-ingress-public:
  controller:
    ingressClass: haproxy-public
    service:
      loadBalancerIP: 172.22.18.64
    stats:
      enabled: true
      port: 1936
    metrics:
      enabled: true
      embedded: true
    serviceMonitor:
      enabled: true
    logs: # access logs
      enabled: true
    config:
      config-frontend: |
        capture request header User-Agent len 100
