apiVersion: v2
name: gitlab-ce
description: GitLab Community Edition continuous integration server.

type: application
version: 0.0.4

dependencies:
- name: gitlab
  version: 5.10.5
  repository: https://charts.gitlab.io/
