apiVersion: v2
name: gitlab-ce
description: GitLab Community Edition continuous integration server.

type: application
version: 0.0.13

dependencies:
- name: gitlab
  version: 6.10.1
  repository: https://charts.gitlab.io/
