gitlab:
  global:
    edition: ce
    gitlabVersion: 15.0.4
    hosts:
      domain:
        k8s
    ingress:
      enabled: true
      configureCertmanager: false
      class: haproxy-private
      provider: haproxy
      annotations:
        cert-manager.io/cluster-issuer: cluster-ca
    psql:
      host: app-database-pg12.database.svc
      port: 6432
      ssl:
        secret: gitlab-pg12-client-cert
        clientCertificate: tls.crt
        clientKey: tls.key
        serverCA: ca.crt
    extraEnv:
      PGSSLCERT: /etc/gitlab/postgres/ssl/client-certificate.pem
      PGSSLKEY: /etc/gitlab/postgres/ssl/client-key.pem
      PGSSLROOTCERT: /etc/gitlab/postgres/ssl/server-ca.pem
    certificates:
      customCAs:
      - secret: cluster-ca-root-cert
  certmanager:
    install: false
  gitlab-runner:
    # Normally used for `gitlab.k8s.crt` certificate, but abusing so our CA root
    # cert is mounted in the runner pods for use with $CI_SERVER_TLS_CA_FILE.
    certsSecretName: cluster-ca-root-cert
    envVars:
    - name: CI_SERVER_TLS_CA_FILE
      value: "/home/gitlab-runner/.gitlab-runner/certs/cluster-ca-root.crt"
  minio:
    ingress:
      tls:
        secretName: minio-tls
    persistence:
      volumeName: gitlab-minio-data
  nginx-ingress:
    enabled: false
  postgresql:
    install: false
  prometheus:
    install: false
  redis:
    master:
      persistence:
        matchLabels:
          app: gitlab
          volname: gitlab-redis-master-data
  registry:
    ingress:
      tls:
        secretName: registry-tls
  gitlab:
    gitaly:
      persistence:
        matchLabels:
          app: gitlab
          volname: gitlab-gitaly-data
    gitlab-shell:
      service:
        annotations:
          metallb.universe.tf/address-pool: private-pool
          metallb.universe.tf/allow-shared-ip: private-main
        loadBalancerIP: 172.22.18.32
        type: LoadBalancer
    sidekiq:
      resources:
        # default requests are pretty chunky at 900m and 2G
        requests:
          cpu: 500m
          memory: 1G
    webservice:
      hpa:
        minReplicas: 1
        maxReplicas: 3
      ingress:
        tls:
          secretName: gitlab-tls
