apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-library-originals-claim
spec:
  volumeName: music-library-originals
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-library-originals
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas
    path: "/storage/media/music/originals"
  mountOptions:
    - nfsvers=4.2
