apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcast-opml-claim
spec:
  volumeName: podcast-opml
  resources:
    requests:
      storage: 200Mi
  accessModes:
  - ReadOnlyMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: podcast-opml
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas
    path: "/storage/k8s/nfs/music/podcast-opml"
  mountOptions:
    - nfsvers=4.2
