apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-extra
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://gitlab.k8s/infra/homelab-apps-extra.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: 'app-{{path.basename}}'
    spec:
      project: default
      destination:
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      source:
        repoURL: https://gitlab.k8s/infra/homelab-apps-extra.git
        targetRevision: HEAD
        path: '{{path}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
