apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: private-pool
      protocol: layer2
      addresses:
      - 172.22.18.32/27
    - name: public-pool
      protocol: layer2
      addresses:
      - 172.22.18.64/27
