apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb

resources:
  - github.com/metallb/metallb/manifests?ref=dbe1a20bb820e2b99337fd658ee40a2bbb53df42 # v0.12.1 tag
  - ./config.yaml
