apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb

resources:
  - github.com/metallb/metallb/config/native?ref=b96bce642175ec99ed4b3e29e552c2e4f7aeaafd # v0.13.7 tag
  - ./private-pool.yaml
  - ./public-pool.yaml
