apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb

resources:
  - github.com/metallb/metallb/config/native?ref=ddd605cc5e9d7b207d28f5ebffa990c00bbd5407 # v0.13.5 tag
  - ./private-pool.yaml
  - ./public-pool.yaml
