apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb

resources:
  - github.com/metallb/metallb//manifests?ref=846c55af003807f1fe4066711607122456509fc4 # v0.11.0 tag
  - ./config.yaml
