- job_name: external-nodes
  scrape_interval: 30s
  metrics_path: /metrics
  dns_sd_configs:
  - type: SRV
    names: ['_node-exporter._tcp.carmel.']
    refresh_interval: 5m
  relabel_configs:
  # set `instance` label to the hostname without trailing period in FQDN
  - source_labels: [__meta_dns_srv_record_target]
    target_label: instance
    regex: '(.+[^.]).?'
    replacement: '${1}'
  # always set `k8s` label to `false`
  - source_labels: []
    target_label: k8s
    replacement: 'false'
  # always set `job` label to `node-exporter`
  - source_labels: []
    target_label: job
    replacement: node-exporter
