- job_name: external-nodes
  scrape_interval: 30s
  metrics_path: /metrics
  static_configs:
  - targets:
    - rpi-fw:9100
    - mail.fewerhassles.com:9100
    - mail.fewerhassles.com:9154
    - k0s-controller.k8s:9100
    - nas:9100
    - ruuvi-bridge:9100
    - snapcast-client:9100
    labels:
      job: node-exporter
      k8s: "false"
  relabel_configs:
  # Keeps explicit `instance`, e.g. from file_sd_configs, but drops port from auto-created `instance` values.
  # Copied from https://stackoverflow.com/a/63414542 .
  - source_labels: [instance]
    target_label: __tmp_instance
    regex: '(.+)'
    replacement: '${1};'
  - source_labels: [__tmp_instance, __address__]
    separator: ''
    target_label: instance
    regex: '([^:;]+)((:[0-9]+)?|;(.*))'
    replacement: '${1}'
