apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: forgejo

namespace: forgejo

resources:
  - ./forgejo-namespace.yaml
  - ./forgejo-helm-manifests.yaml
  - ./forgejo-database.yaml
  - ./forgejo-database-backup.yaml
  - ./forgejo-storage.yaml

images:
  - name: code.forgejo.org/forgejo/forgejo
    digest: sha256:3bde16a366e57f37c09599b77ceb83ed05b1934f8224072f8140bc66cf243608 # 14.0.3-rootless
