# This secret should not be needed because we're using mTLS auth with
# the database.  However, many of the GitLab pods (`migrations`,
# `webservice`, etc.) will will hang out in the `Init` phase until the
# secret is ready.  There is probably a cleaner workaround, but for now
# just create the expected secret with an empty value.
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-password
  namespace: {{ .Release.Namespace }}
data:
  postgresql-password: ""
