apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-master-data
  labels:
    app: gitlab
    volname: gitlab-redis-master-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nas
    path: "/storage/k8s/nfs/gitlab/redis-master-data"
  mountOptions:
    - nfsvers=4.2
