apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: directory
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
      - name: openldap
        image: bitnami/openldap:2.5.13-debian-11-r50
        env:
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openldap-admin
              key: password
#        - name: BITNAMI_DEBUG
#          value: "true"
        - name: LDAP_ROOT
          value: "dc=fewerhassles,dc=com"
        - name: LDAP_ADD_SCHEMAS
          value: "yes"
        - name: LDAP_ALLOW_ANON_BINDING
          value: "no"
        - name: LDAP_CUSTOM_LDIF_DIR
          value: "/ldifs"
        - name: LDAP_CUSTOM_SCHEMA_FILE
          value: "/schema/custom.ldif"
        - name: LDAP_EXTRA_SCHEMAS
          value: "cosine,inetorgperson,nis"
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 1636
          name: ldaps
        resources:
          limits:
            cpu: 50m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - name: openldap-data
          mountPath: /bitnami/openldap
        - name: openldap-config
          mountPath: /ldifs
          subPath: ldifs
          readOnly: true
        - name: openldap-config
          mountPath: /schema
          subPath: schema
          readOnly: true
        securityContext:
          runAsNonRoot: true
      serviceAccountName: openldap
      volumes:
      - name: openldap-data
        persistentVolumeClaim:
          claimName: openldap-data
      - name: openldap-config
        persistentVolumeClaim:
          claimName: openldap-config
