apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: directory
spec:
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: ldap
  - name: ldaps
    port: 636
    protocol: TCP
    targetPort: ldaps
  selector:
    app.kubernetes.io/name: openldap
  type: ClusterIP
