apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docker-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_LOG_ACCESSLOG_DISABLED
          value: "false"
        - name: REGISTRY_LOG_FORMATTER
          value: "json"
        - name: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
          value: "true"
        - name: REGISTRY_HEALTH_STORAGEDRIVER_INTERVAL
          value: "10s"
        - name: REGISTRY_HEALTH_STORAGEDRIVER_THRESHOLD
          value: "3"
        ports:
        - containerPort: 5000
          name: http-registry
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: docker-registry-data
          mountPath: /var/lib/registry
        securityContext:
          runAsNonRoot: true
          runAsUser: 2001
          runAsGroup: 2001
      serviceAccountName: docker-registry
      volumes:
      - name: docker-registry-data
        persistentVolumeClaim:
          claimName: docker-registry-data
