apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  ports:
  - name: registry-http
    port: 5000
    protocol: TCP
    targetPort: registry-http
  selector:
    app.kubernetes.io/name: docker-registry
  type: ClusterIP
